name: telecom_support_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  get_it: ^9.2.0
  dio: ^5.9.0
  dartz: ^0.10.1
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.1
  internet_connection_checker: ^1.0.0+1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  sqflite: ^2.4.2
  path: ^1.9.1
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  uuid: ^4.5.2
  image_picker: ^1.2.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
